### ISSUE TITLE
Create initial screen's "next" button

### ISSUE THREAD

**Issue by billp** [billp/psometer#1]
Create a react component with the following style parameters:
```
font: Manrope Extra Light, 20px, #EDEDED

button: 
    - bgcolor1: #b4f3e7
    - bgcolor2: #64b5a5
    - font: Manrope Extra Light, #EDEDED

```
Animation: ![button-animation](https://user-images.githubusercontent.com/1566052/96885879-b2572f80-148b-11eb-8321-1aa7ad60aa1d.gif)

Requirements:

- I want to be able to set the onClick property of the button.
